"""
History providers - Inject conversation history and summaries.

These providers fill history-related placeholders in the prompt template:
- [CONVERSATION_SUMMARY] - Condensed summary of earlier conversation
- [RECENT_HISTORY] - Recent message exchanges for immediate context
"""

from typing import Optional

from ..build_context import BuildContext, Message
from ..context_provider import ContextProvider


class SummaryProvider(ContextProvider):
    """
    Provides conversation summary for [CONVERSATION_SUMMARY] placeholder.

    Returns the summary text from BuildContext, or None if no summary exists.
    Summaries are typically generated by the summarization plugin when
    conversation length exceeds token budget.
    """

    @property
    def placeholder(self) -> str:
        return "[CONVERSATION_SUMMARY]"

    def provide(self, context: BuildContext) -> Optional[str]:
        if context.summary and context.summary.strip():
            return context.summary.strip()
        return None


class RecentHistoryProvider(ContextProvider):
    """
    Provides recent conversation history for [RECENT_HISTORY] placeholder.

    Formats recent_messages as labeled conversation turns:
        User:
        What's the weather like?

        Spindle:
        I don't have access to weather data, but...

    Uses persona name from context for assistant messages.
    Returns None if no recent messages, causing section to collapse.
    """

    @property
    def placeholder(self) -> str:
        return "[RECENT_HISTORY]"

    def provide(self, context: BuildContext) -> Optional[str]:
        if not context.recent_messages:
            return None

        # Get persona name for assistant label
        persona_name = context.persona.get("name", "Assistant")

        formatted_turns = []
        for message in context.recent_messages:
            label = self._get_label(message.role, persona_name)
            turn = f"{label}:\n{message.content}"
            formatted_turns.append(turn)

        if formatted_turns:
            return "\n\n".join(formatted_turns)
        return None

    def _get_label(self, role: str, persona_name: str) -> str:
        """Map message role to display label."""
        if role == "user":
            return "User"
        elif role == "assistant":
            return persona_name
        else:
            # Fallback for unknown roles
            return role.capitalize()
